id: IC87CA074
source: https://sakyaresearch.org
source_file: null
initial_creation_type: input
imported: '2022-06-18T19:16:56.304140'
last_modified: '2022-06-18T19:16:56.304157'
parser: null
source_metadata:
  title: The Middle-Length Treatise on the Stages of the Path by Tsong kha pa (1357–1419)
    (dGa ldan block print), colophon excerpt
  author: ཙོང་ཁ་པ་བློ་བཟང་གྲགས་པ།
  description: 'Digital version 1.0 {Tibetan}; master xml (completed: 2022-06-02);
    revised, thematic TEI markup'
  file_info:
  - 'Language: Tibetan'
  - 'Coverage: Excerpt/Colophon'
  - 'Accessible: publicly'
  responibilities:
  - Digital edition:ས་སྐྱ་ཞིབ་འཇུག་ཁང་། (src)
  - Text input:Mathias Fermer (mf)
  - Editorial process:David Jackson (dj)
  - TEI Encoding:ས་སྐྱ་ཞིབ་འཇུག་ཁང་།
  - TEI Markup:Mathias Fermer (mf)
  - Revisions/Corrections:Mathias Fermer (mf)
  text_witnesses: https://sakyaresearch.org/sources/329
  bases:
    27bf:
      title: The Middle-Length Treatise on the Stages of the Path by Tsong kha pa
        (1357–1419) (dGa ldan block print), colophon excerpt
      order: 1
      base_file: 27bf.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
